---
# Default
aws_cw_region: sa-east-1
aws_cw_agent_type: 'ec2'
aws_cw_agent_conf: amazon-cloudwatch-agent.json
aws_cw_package_path: https://s3.amazonaws.com/amazoncloudwatch-agent/
aws_cw_config_template_path: 'agent-config-windows.json.j2'

# Monitoring
aws_cw_namespace: MONITORING
aws_cw_collection_interval: 60
aws_cw_logfiles: []
aws_cw_windows_events: []
aws_cw_log_debug: false
aws_cw_disk_monitor_paths:
  - "/"

# Filebeat
filebeat_version: 7.4.0
filebeat_elastic_search_hosts: [""]
filebeat_logging_level: error
index_name:
